-- SELECT` 절에서 열 별칭을 사용하는 경우 `WHERE` 절에서 해당 별칭을 직접 참조할 수 없습니다.
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORDS
from CAR_RENTAL_COMPANY_RENTAL_HISTORY
where MONTH(START_DATE) >= 8 AND MONTH(START_DATE) <= 10
    AND CAR_ID IN (SELECT CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    where MONTH(START_DATE) >= 8 AND MONTH(START_DATE) <= 10
                    GROUP BY CAR_ID
                    HAVING COUNT(HISTORY_ID) >= 5)
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC
