-- GROUP BY로 묶으면 가장 상단의 테이블을 임의로 가져온다 그러므로 SELECT에 MAX를 해도 최대값을 가져오는 개념이 아니다
-- 서브쿼리(한 쿼리안에 SELECT문이 두개 있다.)
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN 
    (SELECT FOOD_TYPE, MAX(FAVORITES)
        FROM REST_INFO
        GROUP BY FOOD_TYPE)
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC;
